[package]
name = "pastey"
version = "0.1.1"
edition = "2021"
license = "MIT"
build = "build.rs"

[lib]
name = "pastey_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.1", features = [] }
tauri-plugin-process = "2"
tauri-plugin-jolt = { git = "https://github.com/alexanderwanyoike/jolt.git", rev = "6a60e67d8e7bd864acb56ddc8b9aa51ea72e6371" }
serde_json = "1"
tauri-plugin-updater = "2"
